pkg/controller/vlan/bridge_vlan_controller.go

**Problem:**
When the network-setting is reset to an empty value the configured status is still showing as `true`
**Solution:**
update the configured status according to the input NIC value
https://github.com/rancher/harvester-network-controller/issues/11

Update network setting when it is empty

---

pkg/bridge/link.go
pkg/controller/vlan/bridge_vlan_controller.go
pkg/dhcp/connman_dhcp.go

**issue**: https://github.com/rancher/harvester-network-controller/issues/14
- fix: connmanctl config nameservers and ipv4
- optimization: do not need to return address if NIC equals configured NIC

fix: connmanctl config nameservers and ipv4

---

pkg/controller/agent/nodenetwork/controller.go
pkg/network/iface/link.go
pkg/network/vlan/vlan.go

To use a macvlan interface rather than the NIC itself if it's used by the management network.
issue: https://github.com/harvester/harvester/issues/980

Use sub-interface

---

pkg/controller/agent/nodenetwork/controller.go
pkg/network/iface/link.go

The network interface will not be down after setting nomaster from the bridge in the new harvester-os.
Related issue: 
https://github.com/harvester/harvester/issues/1464
https://github.com/harvester/harvester/issues/1529

No need to wait down signal after setting no master

---

pkg/network/iface/link.go
pkg/network/iface/route.go
pkg/network/vlan/vlan.go

Related issue: https://github.com/harvester/harvester/issues/1669
The command to configure PVID is different from other VIDs. Assume we
want to configure PVID as 1 and add VID 10 for harvester-mgmt, the commands are as followings.
- Configure PVID 1
`bridge vlan add vid 1 dev harvester-mgmt pvid untagged master`
- Add VID 10
`bridge vlan add vid 10 dev harvester-mgmt master`
The default PVID is 1, so we ignore it.

Ignore default PVID

---

package/Dockerfile
package/Dockerfile.helper
pkg/network/iface/link.go

We won't install ebtables in the new image.
The harvester-br0 only inherits the IP address and routes of the
harvester-mgmt network interface. Meanwhile, the IP address of
the harvester-mgmt could not be changed. Therefore, it's not necessary
to allow the DHCP package to pass to the VLAN interface anymore.
Related issue: https://github.com/harvester/harvester/issues/1868

Migrate base image to BCI image

---

cmd/webhook/main.go
pkg/controller/agent/nad/controller.go
pkg/controller/agent/vlanconfig/controller.go
pkg/controller/manager/clusternetwork/controller.go
pkg/controller/manager/nad/controller.go
pkg/helper/helper.go
pkg/utils/labels.go
pkg/utils/nad.go
pkg/utils/name.go
pkg/utils/vmi.go
pkg/webhook/nad/mutator.go
pkg/webhook/nad/validator.go
pkg/webhook/vlanconfig/mutator.go
pkg/webhook/vlanconfig/validator.go

Related issue: https://github.com/harvester/harvester/issues/3372
Solution: 
- Add a mutating webhook to record the outdated cluster network and VLAN id by `network.harvesterhci.io/last-clusternetwork` and `network.harvesterhci.io/last-vlan-id`. Then controllers are able to know the outdated VLAN id and cluster network to do the cleanup process including deleting the related bridge configuration and route job. 
- All related running VMs need to be stopped before updating VM networks and vlanconfigs. The validating webhook is responsible for the VM checking.
- Indicate the ready status of VM networks by the label `network.harvesterhci.io/ready`. Once the cluster network is unready(no vlanconfig in effect)  , the nad under the cluster network will be unready and can't be used by running …

Support updating VM networks and changing cluster network migration of vlanconfigs

---

pkg/utils/nad.go
pkg/webhook/nad/mutator.go
pkg/webhook/nad/validator.go

The PR solves two problems.
1. Related issue: https://github.com/harvester/harvester/issues/3615
When the mask of CIDR is zero, the route to be deleted would be the default route. We could not delete the default route.
2. Related problem: https://github.com/harvester/harvester/issues/3440#issuecomment-1461784744
It's introduced by the PR https://github.com/harvester/network-controller-harvester/pull/76. 
When the route is empty, it should return nil when checking the route.

Mask of CIDR could not be zero

---

.github/PULL_REQUEST_TEMPLATE.md
pkg/utils/nad.go

**Description:**
When you try to create a VM network, it gives you a webhook validation CIDR error on submission per https://github.com/harvester/harvester/issues/3629
**Solution:**
should validate both CIDR and gateway value when the NAD's route config mode is manual.
https://github.com/harvester/harvester/issues/3629

fix CIDR and gateway validation

---

manifests/crds/network.harvesterhci.io_vlanconfigs.yaml
pkg/apis/network.harvesterhci.io/v1beta1/vlanconfig.go
pkg/controller/agent/vlanconfig/controller.go
pkg/generated/clientset/versioned/fake/register.go
pkg/generated/clientset/versioned/scheme/register.go
pkg/generated/controllers/network.harvesterhci.io/factory.go
pkg/network/iface/bond.go

**Problem:**
The bond will recreate every 10 hour and cause network flapping. 
**Solution:**
- Set default value in the CRD
- Ignore the default value when judging whether there is a parameter change
**Related Issue:** https://github.com/harvester/harvester/issues/3744
**Dependency:** https://github.com/harvester/charts/pull/155
**Test plan:**
- Create a new cluster network and create the related vlanconfig. The default value of miimon and TxQLen is -1. -1 means to keep the original value which may be system default value or set manually before.
- Delete harvester network controller pod, watch `dmesg -T`, the bond will not be recreated.

Avoid bond from recreating periodically

---

package/Dockerfile
package/Dockerfile.helper
package/Dockerfile.webhook

**Problem:**
SLE 15 SP4 general ends on 31 Dec 2023.
**Solution:**
Bump SLE BCI images to to 15.5.
https://github.com/harvester/harvester/issues/4757
**Test plan:**
Test basic operation can work.

feat: bump SLE to 15.5

---

.golangci.json
Dockerfile.dapper
cmd/webhook/main.go
go.mod
go.sum

**Problem:**
Go v1.20 is EOL on 06 Feb 2024.
**Solution:**
Bump golang to v1.21.
https://github.com/harvester/harvester/issues/5310

Bump golang to v1.21

---

pkg/utils/labels.go
pkg/webhook/vlanconfig/mutator.go

**Problem:**
The matched-node returns the whole nodes even if we have one witness node.
The witness node did not run any workload, so we should filter out this.
**Solution:**
we do not allow any workload on the witness node, so we should filter out the witness node when creating the vlan config.
https://github.com/harvester/harvester/issues/5325#issuecomment-2236668074
**Test plan:**
Make sure the annotation of vlanconfig response should looks like below (harvester-node-1 is the witness node)
```
annotations: {network.harvesterhci.io/matched-nodes: "["harvester-node-0","harvester-node-2"]"}
```

webhook/mutator: filter out the witness node

---

pkg/controller/manager/node/controller.go

**Problem:**
Now, the `matched-nodes` will filter out the witness node with creation.
However, the controller has a chance to update the witness node to the `matched-nodes` on the controller part.
**Solution:**
We need to skip to update the `matched-nodes` with the witness node change.
https://github.com/harvester/network-controller-harvester/pull/104#issuecomment-2268030300
**Test plan:**
Make sure the `matched-nodes` annotation of vlanconfig does not contain any witness node.

controller/node: skip update vlanconfig with witness node

---

Dockerfile.dapper
go.mod

**Problem:**
Go v1.21 is going to be EOL soon.
**Solution:**
Bump go version to v1.22
https://github.com/harvester/harvester/issues/6160
**Test plan:**

network-controller-harvester: bump golang v1.22

---

pkg/webhook/clusternetwork/validator.go

**Problem:**
when creating a cluster network using GUI, user specifies a name for cluster network and it is validated for maximum length of 12 at the UI code,but when cluster network with name > 12 chars is created using API, the cluster network is created successfully.
cluster network webhook validator is missing the max length check for cluster network name.
Later it is validated when vlan config is applied on the same cluster network.
But the creation of cluster network should validate it.
**Solution:**
Added create function in cluster network validator to validate for maximum length of cluster network name.
harvester/harvester#3826
**Test plan:**
Manually tested on a harvester node with the changes.

Add validation for max length of cluster network name

---

pkg/network/iface/bridge.go
pkg/network/vlan/vlan.go

**Problem:**
In the Harvester cluster whose management network has a VLAN ID, the VM will be unable to access the host port or node port with the host IP where the VM is running.
**Solution:**
Disable net.bridge.bridge-nf-call-iptables to avoid iptables rules affecting bridge forwarding on vlan.init().
We could not disable net.bridge.bridge-nf-call-iptables in the harvester-installer because RKE2 will enable it after harvester-installer.
**Related Issue:** https://github.com/harvester/harvester/issues/3960
**Test plan:**
- Spin up a Harvester whose management network has a VLAN ID
- Create a VM with VLAN network whose VLAN ID is same with the management network.
- Curl nodeIP:443 in the VM.

Disable iptables bridge forwarding on initialization

---

pkg/network/iface/bridge.go
pkg/network/vlan/vlan.go

(cherry picked from commit 652162909d48f81d2759c49538e2ac42ecd75eb9)
Signed-off-by: Chris Chiu <chris.chiu@suse.com>
**Problem:**
In the Harvester cluster whose management network has a VLAN ID, the VM will be unable to access the host port or node port with the host IP where the VM is running.
**Solution:**
Disable net.bridge.bridge-nf-call-iptables to avoid iptables rules affecting bridge forwarding on vlan.init().
We could not disable net.bridge.bridge-nf-call-iptables in the harvester-installer because RKE2 will enable it after harvester-installer.
https://github.com/harvester/harvester/issues/3960
**Test plan:**
* Spin up a Harvester whose management network has a VLAN ID
* Create a VM with VLAN network whose VLAN ID is same with the management network.
* Curl …

backport: Disable iptables bridge forwarding on initialization

---

pkg/controller/agent/vlanconfig/controller.go
pkg/network/vlan/vlan.go

The DisableBridgeNF() placed in init() would cause phantom error message while restart/kill the network-manager pod. Move it to agent register to prevent the unexpected invoke.
Fixes: 652162909d48 ("Disable iptables bridge forwarding on initializatio")
**Problem:**
https://github.com/harvester/harvester/issues/6747
**Solution:**
Move the DisableBridgeNF() to agent register to prevent the unexpected invoke.
**Test plan:**
1. Manually restarting the `harvester-network-controller-manager` deployment or simply killing off the pod
2. check if there's the error message `disable net.bridge.bridge-nf-call-iptables failed, error: open /proc/sys/net/bridge/bridge-nf-call-iptables: read-only file system`
3.

agent: move the iptables bridge forwarding disable to agent register

---

scripts/build

Backport of https://github.com/harvester/network-controller-harvester/pull/127.

[v0.4] Make the build consistent across archs for Go to correctly report the package path inside the binary

---

scripts/build

Backport of https://github.com/harvester/network-controller-harvester/pull/127.

[v0.5] Make the build consistent across archs for Go to correctly report the package path inside the binary

---

renovate.json

The [default configuration ](https://github.com/harvester/renovate/blob/bf6a43711f19c73e2c96e94132eeac8b630af1c8/renovate-default.json#L6C5-L10)doesn't work for this repo.

ci: tune Renovate base branches [skip ci]

---

.github/workflows/scan.yml

**Problem:**
Github refused to run related job as the required Ubuntu OS is EOL.
https://github.com/harvester/network-controller-harvester/actions/runs/13657731201
```
[Build](https://github.com/harvester/network-controller-harvester/actions/runs/13657731201/job/38181087593)
This is a scheduled Ubuntu 20.04 brownout. Ubuntu 20.04 LTS runner will be removed on 2025-04-01. For more details, see https://github.com/actions/runner-images/issues/11101
Build
GitHub Actions has encountered an internal error when running your job.
```
**Solution:**
Use latest OS
https://github.com/harvester/harvester/issues/4355
**Test plan:**
All PRs should run this job successfully.
Scan.yaml runs successfully.
https://github.com/harvester/network-controller-harvester/actions/runs/13657810131 …

Fix scan.yaml to use ubuntu-latest OS

---

pkg/controller/agent/nad/controller.go

**Problem:**
When updating the VM VLAN Network for fields like vlan, the corresponding vlan is added to the new bridge, but not removed from old bridge.
a.Network controller skips deletion of vlan from bridge (removeLocalArea) when LastKeyNetworkType is empty
**Solution:**
LastKeyNetworkType could be empty but there could be a cluster vlan id update.
PR https://github.com/harvester/network-controller-harvester/pull/149 has bunch of network-controller improvements and webhook checks including "prevention of cluster network updates on a NAD".
https://github.com/harvester/harvester/issues/7676
**Test plan:**
a.create cluster1 ->vlanconfig1 on node1
b.create cluster2 -> vlanconfig2 on node2
c.create NAD1 with vlan 2013 in cluster1
d.create NAD2 with vlan 2013 in cluster2 …

Handle Bridge vlan deletion during nad update

---

pkg/controller/agent/nad/controller.go
pkg/network/iface/link.go
pkg/network/vlan/vlan.go

**Problem:**
During Harvester installation, the system attempts to add all VLAN IDs to the management bond/bridge. With Mellanox ConnectX-6 NICs (which support 512 hardware-offloaded VLANs and have hardware VLAN offloading enabled by default), this causes boot log warnings and prevents management VLAN 2301 from being added to the hardware offloaded VLAN list.
**Solution:**
Dynamically add vlans to mgmt cluster network whenever user creates and updates the nad with mgmt cluster network
This will add vlan associated with that nad to mgmt-bo bridge in linux.
https://github.com/harvester/harvester/issues/7650
**Test plan:**
1.Create NAD with vlan-id and attach it to cluster network mgmt
2.verify if bridge vlan show lists the vlan in the mgmt-bo
3.verify traffic between VMs …

Remove mgmt cluster check during bridge vlan add/del

---

pkg/controller/agent/vlanconfig/controller.go

**Problem:**
vlans are added from previously created cluster networks during a new network config change
This is due to a bug in network controller which lists nads from all cluster network and tries to add it to new cluster network during vlan config change.Instead the listing of NADs should be done only for the cluster network for which the vlan config changed.
**Solution:**
add only the vlans configured part of the new cluster network whenever network config associated with a cluster network change
https://github.com/harvester/harvester/issues/8067
**Test plan:**
a.Create a VM network tagged with vlan id for example 2012,2013,2014 under mgmt cluster
b.Create another cluster network cluster-1 and add network config
c.Check bridge vlan show
Expected result: …

Add vlans only from associated cluster network during network config change

---

pkg/controller/manager/vlanconfig/controller.go
pkg/network/iface/bridge.go
pkg/utils/mtu.go
pkg/webhook/clusternetwork/validator.go
pkg/webhook/nad/mutator.go
pkg/webhook/nad/validator.go
pkg/webhook/nad/validator_test.go
pkg/webhook/vlanconfig/validator.go
pkg/webhook/vlanconfig/validator_test.go

**Problem:**
The empty `linkAttributes` caused panic.
**Solution:**
1. Update the process of accessing `linkAttributes`, avoid panic
2. Add test code to cover the cases.
https://github.com/harvester/harvester/issues/8589
**Test plan:**
1. create a second clusternetwork `cn2`
3.1 create a vlanconfig with empty `linkAttributes` like below
```
apiVersion: network.harvesterhci.io/v1beta1
kind: VlanConfig
metadata:
name: nc4
spec:
clusterNetwork: cn2
uplink:
bondOptions:
miimon: -1
mode: active-backup
nics:
- ens8
```
2.2 create a vlanconfig from Harvester UI, then edit this vlanconfig to remove the whole `linkAttributes`
```
spec:
clusterNetwork: cn2
uplink:
bondOptions:
miimon: -1
mode: active-backup
linkAttributes:  // remove
mtu: 1600  // remove
txQLen: -1 // remove
``` …

Update link attribute processing

---

pkg/utils/subnet.go
pkg/webhook/subnet/validator.go
pkg/webhook/subnet/validator_test.go

**Problem:**
currently "join" and "ovn-default" subnets are ovn cluster default subnets created once the kube-ovn add-on is enabled.
Since network-controller is already running and kube-ovn add-on is enabled later, creation of these subnets happen and network controller webhook validates it for provider length expecting type "nadname.namespace.ovn" but these subnets have a default provider type "ovn". 
**Solution:**
skip subnet validations for default subnets "join" and "ovn-default"
https://github.com/harvester/harvester/issues/8698
**Test plan:**
1.Install v1.6-rc2
2.Enable kube-ovn add-on
3.Kubectl get pods -n kube-system | grep ovn
All ovn related pods must be running successfully
4.harvester-network-webhook pods should not throw any error "invalid provider length 1 …

skip validator checks for default ovn cluster subnets

---

pkg/network/iface/link.go

**Problem:**
Deleting a VM Network on mgmt cluster removes the mgmt vlan causing Harvester node to lose connectivity
**Solution:**
Fix the wrong format to derive the mgmt-br.<vlan-id> interface from Harvester host interfaces 
https://github.com/harvester/harvester/issues/8953
**Test plan:**
1.Mgmt vlan interface is part of vlan 2021 (mgm-br.2021)
2.Create a vlan vm network with tag 2021 and cluster network "mgmt"
3.Delete the vlan VM Network created created in step 2
Expected Behavior:
1VM Network created on vlan 2021 mgmt cluster must be removed for user but 2021 should not be removed from "bridge vlan ..." of mgmt interface on Harvester host.

Fix the mgmt bridge interface format
