harvester/network-controller-harvester

- .drone.yml
- Dockerfile.dapper
- Makefile
- manifests/daemonset.yaml
- package/Dockerfile
- pkg/network/bridge_vlan_controller.go
- pkg/network/settings.go
- scripts/build
- scripts/ci
- scripts/entry
- scripts/package
- scripts/release
- scripts/test
- scripts/validate
- scripts/version
add drone CI and build scripts
> add drone CI and build scripts

- .drone.yml
This reverts commit 9edc311f2f9a90f5f631ac8333b1e72723fb809f.
> Revert "TO REMOVE: add pandaria ci drone"

- pkg/bridge/link.go
> Forbidden nad controller configures default pvid

- pkg/bridge/bridge.go
- pkg/controller/vlan/bridge_vlan_controller.go
issue: #9 
solution: re-fetch bridge at the end of process of ensuring bridge
> re-fetch to ensure br.Bridge has latest attributes

- pkg/controller/vlan/bridge_vlan_controller.go
Network message text enhancement https://github.com/rancher/harvester-network-controller/issues/16
> Network message text enhancement

- manifests/rbac.yaml
- pkg/controller/agent/nad/controller.go
The nad controller should return nil if nodenetwork CR is not found
> Fix nad controller error

- manifests/crds/network.harvester.cattle.io_nodenetworks.yaml
- manifests/rbac.yaml
- pkg/apis/network.harvester.cattle.io/v1alpha1/nodenetwork.go
- pkg/controller/agent/nodenetwork/controller.go
- pkg/controller/common/nodenetwork.go
Fix: https://github.com/rancher/harvester/issues/611
- Remove subresource status
- Initialize nodenetwork status
> Initialize nodenetwork status

- pkg/network/monitor/monitor.go
- pkg/network/vlan/vlan.go
Issue: https://github.com/harvester/harvester/issues/709
Solution:
- Modify the read-write mutex in the monitor package to mutex to ensure that only one `netlink` event is handled at a time.
- Delete routes of harvester-br0 before synchronizing address.
- Watch routes of the slave NIC and transform them to harvester-br0.
> keep default route after address changed

- manifests/rbac.yaml
Related Issue:
harvester/harvester#775
> Fix cluster role

- pkg/network/vlan/vlan.go
Issue: https://github.com/harvester/harvester/issues/709
Solution: If the IP address is not changed, we don't need to synchronize the IP address.
> Ignore the same IP address

- pkg/network/iface/nic.go
Support bond network interface to attach the bridge Harvester-br0.
> Support bond

- manifests/crds/network.harvesterhci.io_clusternetworks.yaml
- manifests/crds/network.harvesterhci.io_nodenetworks.yaml
- pkg/apis/network.harvesterhci.io/v1beta1/clusternetwork.go
- pkg/apis/network.harvesterhci.io/v1beta1/nodenetwork.go
- pkg/controller/agent/nodenetwork/controller.go
- pkg/controller/common/nodenetwork.go
- pkg/controller/manager/clusternetwork/controller.go
- pkg/controller/manager/node/controller.go
- pkg/generated/clientset/versioned/typed/network.harvesterhci.io/v1beta1/clusternetwork.go
- pkg/generated/clientset/versioned/typed/network.harvesterhci.io/v1beta1/fake/fake_clusternetwork.go
- pkg/generated/clientset/versioned/typed/network.harvesterhci.io/v1beta1/fake/fake_network.harvesterhci.io_client.go
- pkg/generated/clientset/versioned/typed/network.harvesterhci.io/v1beta1/fake/fake_nodenetwork.go
- pkg/generated/clientset/versioned/typed/network.harvesterhci.io/v1beta1/network.harvesterhci.io_client.go
- pkg/generated/clientset/versioned/typed/network.harvesterhci.io/v1beta1/nodenetwork.go
- pkg/generated/controllers/network.harvesterhci.io/v1beta1/clusternetwork.go
- pkg/generated/controllers/network.harvesterhci.io/v1beta1/interface.go
- pkg/generated/controllers/network.harvesterhci.io/v1beta1/nodenetwork.go
issue: https://github.com/harvester/harvester/issues/582
> Change CRD to none-namespaced

- pkg/controller/agent/nodenetwork/controller.go
- pkg/network/iface/link.go
- pkg/network/vlan/vlan.go
Reverts harvester/network-controller-harvester#39
> Revert "Use sub-interface"

- main.go
- manifests/deployment.yaml
- manifests/rbac.yaml
- pkg/apis/network.harvesterhci.io/v1beta1/nodenetwork.go
- pkg/config/context.go
- pkg/controller/agent/nad/controller.go
- pkg/controller/agent/nodenetwork/controller.go
- pkg/controller/agent/setup.go
- pkg/controller/common/nodenetwork.go
- pkg/controller/manager/clusternetwork/controller.go
- pkg/controller/manager/node/controller.go
- pkg/controller/manager/setup.go
- pkg/controller/manager/vip/controller.go
- pkg/network/iface/bridge.go
- pkg/network/iface/link.go
Add vip controller to support vip.
issue: https://github.com/harvester/harvester/issues/633
> Support vip

- pkg/network/iface/link.go
Generally, the parent index of the calico veth interface is 3, which is equal to the second NIC. When using the second NIC as the network interface for the VLAN network, the interface whose parent index equals the index of the second NIC will be deleted. The deletion is aimed to clear the macvlan normally, not the veth. We distinguish the interface type to avoid deleting the calico veth atypically.
issue: https://github.com/harvester/harvester/issues/1259
> Only delete macvlan when setting bridge as master

- pkg/controller/agent/nad/controller.go
- pkg/controller/manager/nad/controller.go
- pkg/utils/nadconf.go
Related issue: https://github.com/harvester/harvester/issues/1476
> Set nad vlan-id label

- cmd/network-helper/main.go
- pkg/controller/manager/nad/controller.go
- pkg/helper/helper.go
- pkg/utils/nadconf.go
- Add connectivity initialization
- Add connectivity status "DHCP failed" and "ping failed", delete
"unknown"
- Add pinger timeout and allow 20% package loss
Related issue: https://github.com/harvester/harvester/issues/1476
> optimize the route connectivity

- pkg/network/iface/bridge.go
Related issue: https://github.com/harvester/harvester/issues/1790
> Disable net.bridge.bridge-nf-call-iptables

- pkg/controller/manager/nad/controller.go
Related issue: https://github.com/harvester/harvester/issues/1886
> Fix panic error when nad label is nil

- pkg/controller/agent/vlanconfig/controller.go
- pkg/network/iface/link.go
- pkg/network/iface/route.go
- pkg/network/vlan/vlan.go
Related issue: https://github.com/harvester/harvester/issues/2903
> Remove vlan.localAreas

- pkg/controller/agent/linkmonitor/controller.go
- pkg/controller/agent/nad/controller.go
- pkg/controller/manager/clusternetwork/controller.go
- pkg/controller/manager/nad/controller.go
- pkg/utils/labels.go
- pkg/utils/nadconf.go
- pkg/webhook/nad/mutator.go
- pkg/webhook/nad/validator.go
Related issue: https://github.com/harvester/harvester/issues/1618
> Add untagged network

- pkg/controller/agent/linkmonitor/controller.go
Related issue: https://github.com/harvester/harvester/issues/2988
> Get link state from Link.Attrs().OperState

- pkg/controller/agent/vlanconfig/controller.go
Related issue: https://github.com/harvester/harvester/issues/3337
> GetLocalArea function is not available for untagged network

- .github/workflows/codeql.yml
- .github/workflows/scan.yml
- .golangci.json
- Dockerfile.dapper
- pkg/controller/agent/linkmonitor/controller.go
- pkg/controller/agent/nad/controller.go
- pkg/controller/agent/vlanconfig/controller.go
- pkg/controller/manager/node/controller.go
- pkg/webhook/clusternetwork/validator.go
- pkg/webhook/nad/validator.go
- pkg/webhook/vlanconfig/mutator.go
- pkg/webhook/vlanconfig/validator.go
- Add codeql and trivy CI scanning
- Change dapper build base image to SLE-bci image
- Fix golangci-lint error
> Add codeql and trivy CI scanning

- package/Dockerfile
- package/Dockerfile.helper
- package/Dockerfile.webhook
https://github.com/harvester/harvester/issues/3149
> Bump SLE BCI image to 15.4

- pkg/utils/vmi.go
Related issue: https://github.com/harvester/harvester/issues/3579
> must judge whether nodesFilter is empty

- .gitignore
- pkg/utils/nad.go
- pkg/webhook/nad/validator.go
**Problem:**
https://github.com/harvester/harvester/issues/3580
**Solution:**
Add a CIDR validation to webhook
https://github.com/harvester/harvester/issues/3580
**Test plan:**
https://github.com/harvester/harvester/issues/3580
> add NAD CIDR validation to webhook

- .golangci.json
- cmd/network-helper/main.go
- pkg/controller/agent/linkmonitor/controller.go
- pkg/controller/agent/vlanconfig/controller.go
- pkg/controller/manager/clusternetwork/controller.go
- pkg/controller/manager/nad/controller.go
- pkg/network/iface/bond.go
- pkg/network/iface/link.go
**Problem:**
- Add gosec
- Fix golint warning 
**Solution:**
**Related Issue:** https://github.com/harvester/harvester/issues/4019
**Test plan:**
> chore: Fix golint warning

- .drone.yml
**Problem:**
We don't need to publish binaries when releasing.
**Solution:**
Remove the relevant segment for Drone CI.
**Test plan:**
> ci: remove binary release

- .github/workflows/main.yml
- .github/workflows/pull-request.yml
- .github/workflows/tag.yml
- .github/workflows/template-build.yml
- .gitignore
- Dockerfile.dapper
- package/Dockerfile
- package/Dockerfile.helper
- package/Dockerfile.webhook
- scripts/build
- scripts/entry
- scripts/package
- scripts/version
**Problem:**
replace Drone CI by github action
**Solution:**
Move the image building to github action
https://github.com/harvester/harvester/issues/5327
**Test plan:**
None
> Move image build from drone CI to github action

- pkg/webhook/clusternetwork/validator.go
**Problem:**
cluster network name length is not validated for maximum length when created using API
**Solution:**
Add validation for cluster network max length in webhook validator of cluster network
**Test plan:**
tested manually on harvester node
> 3826 - backport Add validation for cluster network name length

- pkg/webhook/clusternetwork/validator.go
**Problem:**
cluster network name length is not validated for maximum length when created using API
**Solution:**
Add validation for cluster network max length in webhook validator of cluster network
**Test plan:**
Tested manually on harvester node.
> 3826 - Add validation for cluster network name length

- package/Dockerfile
- package/Dockerfile.helper
- package/Dockerfile.webhook
related to https://github.com/harvester/harvester/issues/6568
> Bump bci-base to 15.6
